@library('pipejenkins-shared')
appframeworkAPIsPipline()
def gv
pipeline {
     agent any
    parameters {
        booleanParam(name:'Test', defaultValue: true, description:'this paramater help you to know project name')
        choice(name: 'namespace', choices:['Development','Testing','Production'], description: '' ) 
    }
    stages {
            stage('check') {
                steps {
                    gv.checkapp
                }
            }

            stage('build') {
                steps {
                    gv.buildapp
                }
            }

            stage('test') {
                when {
                    expression{
                        params.Test == true 
                    }
                }
                steps {
                    gv.testapp 
                }
            }
            
            stage('deployment') {  
                steps {
                    gv.deploymentapp
                }
            }    
    }
}

